### ISSUE TITLE
Add approximate requirement in README.md

### ISSUE THREAD

**Issue by dic1911** [uazo/bromite-buildtools#107]
Hello, would you kindly add some info about the requirements such as disk space usage and how long does it take to build on your side to build? thanks.

**Comment by uazo** [comment]
Of course, thank you, I will.

in the meantime, the requirements are the same for the chromium build.
regarding the disk space, indicatively the build image takes up about 36gb, the space instead of the output is 18gb for android and 9.3gb for windows.
you can see my build times of "Build Bromite" workflow in the Actions page.

**Comment by uazo** [comment]
https://github.com/uazo/bromite-buildtools/issues/171

**Comment by uazo** [comment]
https://github.com/uazo/bromite-buildtools/issues/182
