### ISSUE TITLE
[Off-topic] About bromite

### ISSUE THREAD

**Issue by BabyOilJohnson** [uazo/bromite-buildtools#128]
Official bromite app is long behind upstream and outdated since december. Can you give us any updates about the app, is it development stopped or not?

**Comment by uazo** [comment]
Sorry, I know as much as you do.

**Comment by BabyOilJohnson** [comment]
Ok, I thought you are one of the developer of the app. Thanks for the reply.

**Comment by uazo** [comment]
I am, but I have no contact with carl other than public contact via github

**Comment by BabyOilJohnson** [comment]
Ok, for that time being I will use your versions until the stable one gets updated.

**Comment by urmomseksy** [comment]
@uazo instead of creating a new issue I'll just ask here, is this pretty much a drop-in replacement for Bromite?

I'm having a hard time with the current documentation understanding what the difference is are between your app and the original Bromite.

Thanks.

**Comment by uazo** [comment]
>  what the differences are between your app and the original Bromite.

well, you are right, is not written anywhere.
it was never my intention to use this repo except for my experiments on bromite.

it's hard to answer your question in detail, because in my browser there are all the bromite patches (but updated by me to 112) and others of mine that would have been happy to merge into bromite (but the process got stuck).
is an activity that will be part of the documentation process for this repo, if I ever decide to do it.

**Comment by urmomseksy** [comment]
> > what the differences are between your app and the original Bromite.
> 
> well, you are right, is not written anywhere. it was never my intention to use this repo except for my experiments on bromite.
> 
> it's hard to answer your question in detail, because in my browser there are all the bromite patches (but updated by me to 112) and others of mine that would have been happy to merge into bromite (but the process got stuck). is an activity that will be part of the documentation process for this repo, if I ever decide to do it.

Thank you.

If there is anything some of us can help with regarding documentation, let us know.
