### ISSUE TITLE
Migration guide / Build with Bromite package name

### ISSUE THREAD

**Issue by D3SOX** [uazo/bromite-buildtools#160]
I'd like to migrate my current official Bromite 108 installation to this, but I don't want to lose all my data.
Can you provide builds with the Bromite package name? I'm rooted so I can bypass signature vertification using CorePatch.
Or is there any other way to import browser data?

**Comment by bioluks** [comment]
@D3SOX Had the same question, which data exactly? Browser history wasn't important for me. I had hundreds of open tabs, needed to recover those. [Just follow this guide](https://android.stackexchange.com/a/104153), for me it worked (of course root needed). Some things to consider when following this guide:
For me the Bromite Path was `/data/data/org.bromite.bromite`. When you export this file it will have a strange formatting. If you want all the URLs in a readable format for importing it to your PC etc. you might want to fix that, for this [use this command](https://android.stackexchange.com/questions/56635/how-can-i-export-the-list-of-open-chrome-tabs/104153#104153:~:text=Re%20%22special%20text,at%2018%3A30)
If you want to directly transfer all tabs to other android chromium browsers, you _**could**_ try copying over the files (tab_state and the other tab files too) while protecting the same folder structure into uazo Bromite's install path, no guarantee for this to work since I never tested this method.

**Comment by uazo** [comment]
https://github.com/uazo/bromite-buildtools/issues/182
