### ISSUE TITLE
Remove GetInstalledRelatedApps API support

### ISSUE THREAD

**Issue by j0lol** [uazo/bromite-buildtools#177]
PWA app icons look different compared to chrome upstream:
![Screenshot_20230505-014231_Trebuchet.png](https://user-images.githubusercontent.com/24716467/236357754-5ddb8d2f-f31f-4cde-a6dd-2788d6569ebc.png)

is there a reason for this? it looks unpleasant.

**Comment by uazo** [comment]
please explain the steps you have taken.
I would like to check which patch changes the behaviour.

**Comment by j0lol** [comment]
i have chrome and this patched version both installed, and i installed a PWA using each (you cannot use the same website as having a PWA installed by Chrome will make the "Install App..." item change to "Open PWA")

the websites i used in this example are elk.zone and tube.cadence.moe, any PWAs with proper icons should work for this though...

**Comment by uazo** [comment]
check also [Disable add to home screen prompt](https://github.com/uazo/bromite/blob/next-v113/build/patches/Disable-add-to-home-screen-prompt.patch)

**Comment by uazo** [comment]
the mechanism looks like this.

when each site is opened, it is asked to download the manifest file where is present the information, i.e., whether the site exposes a pwa.
if it is present, the menu becomes "Install App" otherwise "Add to home screen".

the code then, based on the menu, generates a link with two different intents ([createWebappShortcutIntent](https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:chrome/android/java/src/org/chromium/chrome/browser/ShortcutHelper.java;drc=e0e0d24aaa54727dc0a8bc4b159ccdf80d3f5d8d;l=192) and [createShortcutIntent](https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:chrome/android/java/src/org/chromium/chrome/browser/ShortcutHelper.java;drc=e0e0d24aaa54727dc0a8bc4b159ccdf80d3f5d8d;bpv=1;bpt=1;l=234)) which will open in the first case the pwa in chromium full screen, in the second case the tab opening if the url is present or a new page in the browser.

However, the code that generates the icon is the same, and the behavior is identical in my device whether with the current v113 or v108 version. The emulator, on the other hand, behaves differently
I can't explain why behaves differently though.

In the meantime, however, I also found the GetInstalledRelatedApps() function on the blink side, through which it is possible for the site to know whether its pwa is present in the device.
[docs](https://github.com/WICG/get-installed-related-apps/blob/main/EXPLAINER.md): for what I think it should be disabled.

**Comment by uazo** [comment]
fixed in https://github.com/uazo/bromite/commit/41678f396299cc4e474f7dc93e327df7b7bdd684

**Comment by uazo** [comment]
the test is missing

**Comment by uazo** [comment]
I need to clean up the issue list, so: 
tracking issue https://github.com/uazo/bromite-buildtools/issues/230
