### ISSUE TITLE
What have I to do for building on linux ??

### ISSUE THREAD

**Issue by LeOS-GSI** [uazo/bromite-buildtools#180]
Sorry, but I don't understand you HowTo. What Have I to do to get the build script running on Linux ? You only have a windows setup described ?

And will you script apply ALL bromite patches ??

**Comment by uazo** [comment]
I am not able to compile for linux, or rather, I have never done it because I don't have a desktop environment with which to test it.
Some of my patches would not work because I deliberately (for the reasons given above) did not evaluate linux-specific code.

> Have I to do to get the build script running on Linux ?

you can try my docker images, see https://github.com/uazo/bromite-buildtools/issues/59#issuecomment-1454742907
the name of the image can be found in the link attached to the release

> And will you script apply ALL bromite patches ??

yes, all of them and more. In fact, to say that this browser is bromite is no longer accurate.
you can see it from [bromite_patches_list.txt](https://github.com/uazo/bromite/blob/next-v113/build/bromite_patches_list.txt)
bromite's patches are up to [L197](https://github.com/uazo/bromite/blob/next-v113/build/bromite_patches_list.txt#L197).
after that those are mine, never verified and checked by carl, for the record.
although by now saying they are bromite's patches is no longer accurate because since v112 I have started cleaning and joining them.

**Comment by uazo** [comment]
@LeOS-GSI I simply close to clean up the issue list.
is tracked in https://github.com/uazo/bromite-buildtools/issues/259

you may also be interested in https://github.com/uazo/bromite-buildtools/issues/193
