### ISSUE TITLE
Remove extension support in windows?

### ISSUE THREAD

**Issue by uazo** [uazo/bromite-buildtools#184]
What doesn't the browser do today without extensions?

my current setup
![image](https://user-images.githubusercontent.com/29201891/236610977-284f3df6-8d2f-4af2-b0af-c7cade70e8b2.png)

Does cookie autodelete really do what I think it does?
Do those extensions have access to the network? Do they introduce additional fingerpriting?

- [ ] check [remote_host_contacted_signal_processor](https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:chrome/browser/safe_browsing/extension_telemetry/remote_host_contacted_signal_processor.cc)

**Comment by welkinpc-91** [comment]
All I know is that additional extensions of any kind ADD fingerprint.

It's for example recommended to no install anything else on Tor, and not uninstall or install anything more on Mullvad Browser.

Mull requires you to install uBlock and NOTHING else to blend with the other users.

From what I've seen online it's the same for Chromium based browsers. (Even with Brave that supposedly randomizes fingerprint)

Hell, privacy guides even suggests not turning on additional Adblocking filter lists on Brave (internal adblock) or on uBlock Origin (extension), as even those add a fingerprint. (Which means Europeans like myself are SOL)

**Comment by imagecreation** [comment]
Well, I personally use some Violentmonkey scripts (can't live without them), uBlock Origin is way more comfortable to use as adblocker, LibRedirect helps to redirect bad for privacy websites like youtube, twitter, tiktok etc etc to their open source privacy friendly frontends. And some private extensions.
![image](https://user-images.githubusercontent.com/128193454/236876757-112a3435-b401-41a5-9e90-71f4142192f3.png)
I don't think all this functionality can be embedded in web browser.

As for internet access - I personally monitor browser leakage with Wireshark to make sure nothing pings.

**Comment by dl12345** [comment]
Removing extensions would be a surefire way to get me to  not use the windows version of bromite. Why take the choice away from the user? 

Most users who install bromite are sophisticated enough to understand the risk that extensions pose. Let the user decide whether or not to use extensions. Perhaps add a flag and default to disabled if you're concerned about naive users.

In certain cases, I need to browse with cookies enabled, and Cookie Autodelete is absolutely indispensable for this use-case, as is EditThisCookie for its ability to selectively block certain cookies. In fact, Cookie Autodelete is so awesome that I wish its functionality were embedded directly in the browser.

I also use a bypass paywalls extension that requires cookies to be on. Extension support is a must-have and makes my own browsing experience more private in the case that I'm browsing with cookies enabled. I don't want to have to manually clear cookies and local storage or restart the browser. I want them nuked the second I close the tab.

Because very few Android browsers have extension support, I even have Kiwi browser installed alongside bromite for those use-cases, just so that I can use Cookie Autodelete. However, Kiwi leaks like a sieve and I have had to spend considerable time hardening it, including with a few custom extensions I wrote to block webgl, strip out client hints headers and change http referer policy, in addition to running a few web store anti fingerprinting extensions that aren't in their entirety satisfactory and which I'm rewriting. 

I dislike running leaky Kiwi so much that I've even spent a fair bit of time looking to see if I can modularize its android extension support so that it can be applied to bromite, but that's a really difficult task due to the large number of patches required.

So no, I think taking the choice away from the user is a very bad thing.

And thanks a ton @uazo for ressurecting bromite. It's my go-to daily driver on Android.

**Comment by dl12345** [comment]
> Does cookie autodelete really do what I think it does? Do those extensions have access to the network? Do they introduce additional fingerpriting?

There's an extension in the chrome webstore that lets you download the source code for any web store extension as a zip file. I do this and review the source code before using it. In some cases, I modify it and install the extension in developer mode so it's not attached to the chrome web store, for greater security.

Some extensions do need network access. For example to download lists, such as ublock. Many don't. It really depends on what the extension is designed to do.

And yes, as you probably surmised from my other reply, Cookie Autodelete does do what the name implies: it will clean all cookies and optionally local storage, cache, service worker storage etc when you close a tab. It's mainly for people who browse in tabs, as I do. I never directly click on a link - always right click or long press in Android and open in a new tab. It's probably the greatest extension ever written after ublock.

The vast majority of extensions won't introduce additional fingerprinting. It's the anti-fingerprinting extensions that do it wrong that pose the problem.

My extension I wrote for Kiwi to block webgl looks just like bromite does on the webgl test on browserleaks.com. It simply intercepts calls to HTMLCanvasElement.getContext, checks the argument to see if it is webgl and returns null if it is, effectively disabling the webgl api as per the specification (a null return means not supported or disabled), instead of naively trying to randomise the fingerprint as does at least one other 3rd party extension. Fingerprint randomisation can be detected if done incorrectly. Brave randomises it, but does so properly, although Brave only resets the webgl fingerprint to a new one when the browser session is restarted (for compatibility reasons) or you browse a new eTLD+1. I prefer it simply disabled - amiunique.com/fp reports somewhere north of 14% of browsers have webgl disabled, so it's a safe technique 

Only if an extension is deliberately adding headers or fiddling with any of the javascript apis to alter the output or functionality in a new and unique way would it create additional fingerprinting. You'd have to work quite hard to achieve that and it would probably need to be deliberate. It's unlikely to happen by accident.

**Comment by Universalizer** [comment]
Hello, All of you, good discussion and reviews here,

@uazo, thanks for opening these issue, in general for desktop,
1) Only privacy centric/enhancing extensions must be entertain,<hr>

If uBo (uBlock Origin) is best choice, than no other content blocker.

https://github.com/gorhill/uBlock/wiki/uBlock-Origin-works-best-on-Firefox

https://github.com/gorhill/uBlock/wiki/Does-uBlock-Origin-block-ads-or-just-hide-them%3F#hosts-file

https://github.com/gorhill/uBlock/wiki/Scientific-papers

**Must check**
https://brave.com/learn/best-ad-blocker/<hr>

2) that too minimum (in limited numbers, lesser the better),
3) as per essentially requirement.

4) Lastly, exceptions "as per user needs or requirements as a choice (willingly opted-in, but must be carefully, at his own risk)".

@welkinpc-91, no doubt, you are absolutely right,👍keep it up.

@imagecreation,
> I don't think all this functionality can be embedded in web browser.👍<hr>

@dl12345, good observation on ki,wi browser👍
> always right click or long press in Android and open in a new tab.👍

**Sorry, off the topic, but new suggestion (as an idea here), whether good or not ❓**

Default behaviour ; for opening "any links from current webpages within the browser", should be "in a new tab".

A toggle in a, menu > settings > open links in new normal (ntp) or private tab > toggle "on or off".

Feel free to express your opinion.

**Comment by ferromint** [comment]
> @uazo [...] Remove extension support in windows? [...]

No, please keep it.

> @dl12345 [...] Removing extensions would be a surefire way to get me to not use the windows version of bromite. Why take the choice away from the user? [...]

I fully agree.

> @dl12345 [...] Because very few Android browsers have extension support, I even have Kiwi browser installed alongside bromite [...]

That is why I am using Firefox Nightly for Android and had/have Bromite installed alongside Firefox (so other way round in my case).

@uazo
Actually please go in the opposite direction and enable the support for extensions on Android!

> @imagecreation [...] I don't think all this functionality can be embedded in web browser [...]

Actually it shouldn't be directly integrated
- as it takes hundreds or thousands of hours of work to develop even only one of the more advanced extensions so that it works reliably up to that point (quality and speed) that those extensions have achieved until today. You simple can't do all this work alone or even with just a few developers! That is the whole point of shifting features from the main browser to extensions to make the browser a flexible toolkit and not a monolith!
- not every user wants to use certain tools which do undoubtedly increase the memory footprint, complexity and also chance for errors (yes, bugs also happen with the most well-tested pieces of software especially in the field of web browsers)

**Comment by uazo** [comment]
thanks to everyone!

this issue is complex and honestly still unclear to me. I don't have a definite position yet; I'm thinking about it.
I'm just giving a few examples of what I see on my friends' PCs, which are totally non-technical: never seen any extension installed (other than adblock)
I would like to provide a ready-to-use (and working) browser with everything I imagine would be useful.
in addition there would also be the issue of privacy even in the extensions, which have so much, maybe too much, power without the user having control.

**Comment by DKB-91** [comment]
While I may have given info I've found out on the web, I am for freedom of choice, so while I'll personally avoid installing too many extensions or only an adblocker (on Firefox), I am in favor of keeping the extension support.

Besides I too occasionaly use them (in compartmentalized profiles)
Hell, I have set up a profile for just Youtube browsing since it takes 6+ extensions to make the website bearable. 🤣 (Still waiting for Freetube to add livestream tab support, Newpipe too, but the latter doesn't make me run off to firefox android as there are workarounds)

If you want to push a privacy focused browser, maybe just a pop up / text box about the dangers of installing too many or certain types of extensions, and how they impact fingerprinting.
So let the users have the final word once they have been informed.

Besides next year MV3 or whatever it's called is going to roll out IIRC? 
That will severely limit and break some extensions like uBlock Origin and Violentmonkey.
So there's no need to limit extensions abilities when mainstream Google is already on it 😅

**Comment by uazo** [comment]
You see?

- [uBlock Origin](https://addons.mozilla.org/firefox/addon/ublock-origin/) --> Integrate Adblock plus
- [Skip Redirect](https://addons.mozilla.org/firefox/addon/skip-redirect/) --> Incoming Bounce Tracking Mitigations (wip in chromium), workaroud, always incognito, delete data at startup/close down
- [CanvasBlocker](https://addons.mozilla.org/firefox/addon/canvasblocker/) already internally present and as far as I know CanvasBlocker does not act in service workers
- [Smart Referer](https://addons.mozilla.org/firefox/addon/smart-referer/) already internally present
- [Behave](https://addons.mozilla.org/firefox/addon/behave/) wip in https://github.com/uazo/cromite/issues/344

- [Header Editor](https://addons.mozilla.org/firefox/addon/header-editor/) and [Request Control](https://addons.mozilla.org/firefox/addon/requestcontrol/) I don't understand the purpose of it

[Redirector](https://addons.mozilla.org/firefox/addon/redirector/) this could discussed

**Comment by imagecreation** [comment]
Well, I don't think internal adblock can have this feature - https://github.com/gorhill/uBlock/wiki/Blocking-mode
And even medium mode helps a lot to block trackers and malicious scripts.

**Comment by dl12345** [comment]
Those links are all Firefox extensions, not Chrome ones. That said, there are either Chrome versions of most of those or similar extensions

> You see?
> 
> * [uBlock Origin](https://addons.mozilla.org/firefox/addon/ublock-origin/) --> Integrate Adblock plus

I use numerous advanced features of uBlock. I ignore the inbuilt adblock (in browsers that have it) as I can't add custom filter expressions or use those advanced features.

> * [Skip Redirect](https://addons.mozilla.org/firefox/addon/skip-redirect/) --> Incoming Bounce Tracking Mitigations (wip in chromium), workaroud, always incognito, delete data at startup/close down
> * [CanvasBlocker](https://addons.mozilla.org/firefox/addon/canvasblocker/) already internally present and as far as I know CanvasBlocker does not act in service workers

To intercept the calls to HTMLCanvasContext, the code needs to run in the page context and not in the service worker. The service worker just contains message listeners and code to add and retrieve settings from local storage (I checked the Chrome variant of the code). Service workers can't directly access the HTML and JS code in pages. Page context scripts can't access the Chrome API. 

> * [Smart Referer](https://addons.mozilla.org/firefox/addon/smart-referer/) already internally present
> * [Behave](https://addons.mozilla.org/firefox/addon/behave/) wip in [Add UI for INSECURE_PRIVATE_NETWORK site setting (default disabled) #105](https://github.com/uazo/cromite/issues/344)
> * [Header Editor](https://addons.mozilla.org/firefox/addon/header-editor/) and [Request Control](https://addons.mozilla.org/firefox/addon/requestcontrol/) I don't understand the purpose of it

These allow rewriting of http request headers. I use extensions like this to strip out SEC-UA client hints headers on browsers where there's no inbuilt control. These headers are (IMHO) a horrible privacy problem. They're ostensibly there to reduce dependence on the user-agent header by imposing a requirement on the server to explicitly request the info rather than just sending a detailed user-agent string every time. But if a server routinely requests it, you can't prevent it except by rewriting the headers. 

> 
> [Redirector](https://addons.mozilla.org/firefox/addon/redirector/) this could discussed

Please don't decide for users whether they can use extensions. It's unnecessary to be so proscriptive. If you're concerned about naïve users, put a new chrome://flags in to disable extensions, set it to disable by default, and give the user who understands what they're doing to ability to turn extensions back on. That's easy to implement and maintains the functionality if the user decides they want it. 

This browser will mostly be used by people who understand what they're doing, technical users as opposed to untechnical users. The unsophisticated user won't even know to look for it or understand the implications of the features it offers.

**Comment by DKB-91** [comment]
The only big problem about uBlock Origin (at least on Chromium, Firefox will hopefully make this kickass adblocker live on with their custom MV3) is that it's end of life (again, on chromium) is approaching.

MV3 will severely limit or outright break it, so while it is the best content blocker bar none, internal adblocks are indeed the way to go for Chromium browsers.

I am unsure how internalizing it is going to work as you'll have to fork it and mantain it, since it's creator has given up on making it work on MV3 Chromium in favor of uBlock Lite, which is just laughable compared to an advanced uBlock Origin configuration.
Which means that assuming Mozilla does good on their word of including in their MV3 the protocol that makes adblockers works as they do now, uBlock Origin will be  Firefox exclusive.

The other extensions are fair game, but [not aged well comment] I've could've sworn that every other fork of chromium has auto-deleting cookies on tab close built in in their cookie settings (Brave and when I used it Vivaldi did), unsure if it's as powerful or through as the extension, but it is possible (I think) to internalize it.[not aged well comment]
Still, going to echo what I already wrote, extensions add fingerprint but user choice is the most important factor, let people decide.

Edit: looking more into the cookie extension I've figured it works differently than I've thought, to replicate it using the inbuilt chromium delete on tab close you would have to make too many site settings, discard what I wrote about it 🤣

**Comment by Universalizer** [comment]
### Sorry again, If off the topic, but much important matter, as Uazo you are witness, on this discussion.

On 2023 Apr 14, My Discussion to uazo and xarantolus.

https://github.com/Universalizer/Universaliser_Filters/discussions/3#discussioncomment-5618967

> My Observation for this specific filter, as follows :-
245,884 network filters ＋ 11 cosmetic filters
245,831 used out of 441,817,

245,831 (effective) out of 441,817 (total),

Is "Manifest v3" already arrived & hitting ⁉️

Whereas today's 2023 May 13,
23,985 network filters ＋ 0 cosmetic filters from:

From SAME FILTER with medium changes (modification ; after our discussion) to improve the effectiveness of filter.
same approximate numbers (hardly difference in few thousand only)

What to understand ⁉️

**Comment by DKB-91** [comment]
From what I remember it shouldn't be the case, not this soon.
MV2 extensions downloads should sunset next month/end of this month (so no more installing uBlock Origin and the like from the store) and MV3 will roll out next January...unless they've delayed 6 months again. (Which would mean MV3 next June)

I've had a similiar experience in the past when I was less knowledgeable in adblocks, with Firefox w/uBlock Origin, and the reason at the time was activating overlapping filter lists.

IIRC it was Fanboy's lists, I never knew Fanboy's Annoyance included Fanboy's Social and Fanboy's News letter, and that some Adguard filters overlap with Easylist.

So basically the total filters added the maximum rules count up but only half counted as active because uBlock wouldn't count the same overlapping rule twice. (So the lesson was activate less filters not only because of fingerprint, but because of impratical bloat 🤣)
 
If it's not that some nasty bug is in play, becausd that's...not good.
Doesn't help that those numbers are eerily similiar to uBlock Lite numbers, because MV3 won't let more than 30.000 rules per extension... (IIRC?) 

With uBlock Origin on Uazo's Chromium in windows and Firefox I get the usual 240.000 rules active, Brave and the internal adblock of Uazo's do not give numbers but work...so I think a bug is your case, even with too many overlapping filters, that number is too low for anything that isn't a MV3 extension.

**Comment by welkinpc-91** [comment]
This is weird, also don't know much about Kiwi Browser since I don't really use it.

My only guess is they haven't used the enterprise version of chromium (IIRC?) that extended MV2 lifespan to this year, but that sounds crazy since it has been delayed even for non enterprise version to work until next month.

[https://developer.chrome.com/docs/extensions/migrating/](Manifest V3 was rolled out in 88)

[https://arstechnica.com/gadgets/2022/12/chrome-delays-plan-to-limit-ad-blockers-new-timeline-coming-in-march/(The last update about MV3 delay I've found, store availability ends up in January 2024)

The limited rules active seem to imply MV3 usage instead of MV2 (for Kiwi, but if I understood correctly you also mentioned Mull? It shouldn't be possible.)

**Comment by welkinpc-91** [comment]
Hold up, what list(s) do you have active? 

I have far more active lists than yours (all ublock actives + privacy + region + urls), so I reach the 260.000 number quite easily, do you only have Easylist on? Or the Easylist of your region?

The former would be worrying as Easylist is 67.176 rules but the latter would make sense, Easylist Italy for example is only 13,605 rules long at the moment.

Does it show you the maximum number of your list? Is it anything close to the active number?

![Screenshot_20230513-202714_Mull.jpg](https://github.com/uazo/bromite-buildtools/assets/124310619/cc205f53-c7e7-4851-82a0-6db5a7b92181)

Like see here, it shows how many rules are active/not overlapping compared to the filter list lenght.
Yeah I know I've not optimized enough for privacy or bloat, but it's what works for me the rare case I need Mull or on Firefox desktop. (Both share the same advanced rules and filters, lazy I know)

If your total active lists are only 25.000 long it would make sense. (I remember Easylist once being more than 67.000 rules long, keep in mind they always add, remove or change rules periodically for disuse, breakage, or more encompassing rules)

If it's not something it's acting up, but you'd need to take it up with either the uBlock dev or the filter(s) maintainer(s).

**Comment by kowith337** [comment]
Then need to leave acceptable ads in ABP to user decision for opt-in or not, if not, don't!

**Comment by DKB-91** [comment]
I'm not sure how and if "taking inspiration" from other browsers can lead to trouble (History as shown Brave devs to be very...aggressive), but Brave is rolling in the near future Forgetful Browsing, deleting first party cookies upon site exit (I assume all tabs from website closed?)

It says: "Forgetful Browsing clears both explicitly stored values (e.g. cookies, localStorage(opens in new tab), or indexedDB(opens in new tab)) and indirectly stored values (e.g. HTTP cache or DNS cache)."

Assuming delete cookies works the same way on tab closed, this is something that if it is easy to replicate could be, time and resources allowing, in the future, be implemented in the browser itself?

It seems worth looking into at least, but for maximum user choice and satisfaction, extensions should still be supported. (As far as Chromium and mainstream Google will allow at least)

**Comment by dl12345** [comment]
> I'm not sure how and if "taking inspiration" from other browsers can lead to trouble (History as shown Brave devs to be very...aggressive), but Brave is rolling in the near future Forgetful Browsing, deleting first party cookies upon site exit (I assume all tabs from website closed?)
> 

I've been playing with this Forgetful Browsing feature a bit on the Desktop version of Brave nightly, as it's the only one that has the functionality.

The android nightly is yet to roll it out (only available in 1.54). It works well and is a very nice feature for a mobile browser and would obviate the need for cookie autodelete in probably the majority of use-cases, although it's a bit of a blunt instrument. 

I still would not be able to swap out this feature for cookie autodelete on my desktop browser due to needing to retain cookies from some sites for single sign on functionality. It needs a whitelist or greylist capability to be a true replacement, but it's an excellent feature to have in a mobile browser that doesn't support extensions.

I haven't looked at the Brave patches for this feature yet, so don't know if they can be applied to this browser without a large amount of effort, but if they can be applied then it would be a fabulous addition to Bromite / (Chromite?) or whatever has been decided as the new name for this browser.

**Comment by uazo** [comment]
moved to https://github.com/uazo/cromite/issues/256

**Comment by uazo** [comment]
please @foxjaw rewrite it into https://github.com/uazo/cromite/issues/256

>  You'd always get a better uBO experience in firefox. 

can you also write down why?

**Comment by serdarth** [comment]
> can you also write down why?

See the reasoning from uBO's creator.

https://github.com/gorhill/uBlock/wiki/uBlock-Origin-works-best-on-Firefox
