### ISSUE TITLE
Is there no more update?

### ISSUE THREAD

**Issue by HJMVR** [uazo/bromite-buildtools#335]
The last update I can find is from July 2023. Have I missed where the new updates are or that they no longer is released?

**Comment by BugReportI** [comment]
> The last update I can find is from July 2023. Have I missed where the new updates are or that they no longer is released?

This is repository is not updated anymore. The updated and maintained repository is here https://github.com/uazo/cromite.

@uazo, is it possible to change the status of this repository to not maintained/updated and place a link to updated and maintained repository, so others who have same question know where to go?

**Comment by uazo** [comment]
>  Have I missed where the new updates are or that they no longer is released?
>  place a link to updated and maintained repository

see https://github.com/uazo/bromite-buildtools/releases/tag/v115.0.5790.98-30d36db90516e651c2cd676a677268b3ea7cf75b
the indication is already there.

>  status of this repository to not maintained

no, because I use it instead :)

**Comment by BugReportI** [comment]
If you are still using this repository, than it might be better to put the link to where to get latest Cromite from in Readme and make it clear this is not the repository to get latest Cromite anymore.

I think some users may not bother to check the release page, thinking it is outdated since it shows last release in July.
