### ISSUE TITLE
Feature Request: DNS-over-HTTPS/3 (or even better DNS-over-QUIC)

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [uazo/bromite-buildtools#55]
I think "Feature Request" and/or "Discussions" should be added to this repository.  Any chance of integration of DNS-over-HTTPS/3 into this fork of Bromite? Google, supposedly, already had it integrated into Google Play system update almost half a year ago - https://security.googleblog.com/2022/07/dns-over-http3-in-android.html .

**Comment by uazo** [comment]
> Any chance of integration of DNS-over-HTTPS/3 into this fork of Bromite? 

Is currently in development https://chromestatus.com/feature/5154357283651584.

can you give me some indication with regard to privacy?
the benefit, in terms of latency, should be understood, considering that the 0-rtt should be switched off with the tls resumption switched off

**Comment by GY8VSdYYzvL8-K6T** [comment]
No, I think DoQ is much better for privacy than DoH/3. DoQ is more difficult to implement than DoH/3, but DoH/3 is going to gain more traction and support as a standard. I simply don't expect anyone except for 3rd parties (like AdGuard for Android) to implement DoQ into Android or Chromium. There is no privacy benefit, only speed, latency, prevention of TCP bufferbloat, making it easier to switch networks, etc.  There is that and the fact that analysis/forensic tools, governments and security firms have caught up with DoH/2, but not DoQ and/or DoH/3.

**Comment by GY8VSdYYzvL8-K6T** [comment]
There is a way to implement Perfect Forward Secrecy with 0-RTT, but I am not sure whether that's a server-side thing or client-side thing - https://eprint.iacr.org/2017/223.pdf .

**Comment by uazo** [comment]
> I think DoQ is much better for privacy than DoH/3

I am not so formed to be able to make a judgement. what I assume is that dns over http (whatever version it is) is not identifiable at the network level because it is similar to other http calls (also considering masking of the sni with ech).

> There is no privacy benefit

that's what I imagined, so I am closing this issue.

>  implement Perfect Forward Secrecy with 0-RTT

the point, in my opinion, is a different one.
if it is true that to use 0-rtt you need an already established tls session key, using an extension like cookie autodelete becomes useless, since potentially the server has the ability to recombine different http calls using the tls key already exchanged in previous sessions.
